---
### New playbook
- hosts: webservers
  vars_files:
    - vars.yml
  remote_user: "{{ remote_sudo_user }}"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  roles:
    -
     role: common
     tags: [init]
    -
     role: user
     tags: [init, user]
    -
     role: ssh
     tags: [init, ssh]
    -
     role: nginx
     tags: [nginx, web]
    -
     role: nginxsites
     tags: [nginx, web, sites]
    -
     role: php
     tags: [init]
    -
     role: mariadb
     tags: [init]
    -
     role: wp-cli
     tags: [init]
    -
     role: wordpress
     tags: [web, wordpress]
    -
     role: importdb
     tags: [web, wordpress, import]
    -
     role: letsencrypt
     tags: [web, ssl]
    -
     role: gitdeploy
     tags: [deploy]
    -
     role: logentries
     tags: [logentries]
    -
     role: geerlingguy.nodejs
     tags: [node]
    -
     role: grunt
     tags: [grunt]
    -
     role: geerlingguy.composer
     tags: [composer]
    -
     role: geerlingguy.redis
     tags: [redis]
    -
     role: php-redis
     tags: [redis]