---
- block:
  - name: Creates directory for domain web files
    file:
      path: '/home/{{ remote_web_user }}/www/{{ domain }}'
      state: directory
    tags:
      - production

  - name: Create logs directory
    file:
      path: '/home/{{ remote_web_user }}/www/{{ domain }}/logs'
      state: directory
    tags:
      - production

  - name: Generate random password for wp db user
    command: php -r "echo md5(random_bytes(10));"
    register: db_pass

  - name: Create WordPress database
    mysql_db:
      name: '{{ wpdbname }}'
      state: present

  - name: Create WordPress database user
    mysql_user:
      name: '{{ wpdbname }}'
      password: '{{ dbpass.stdout }}'
      priv: "{{ wpdbname }}.*:ALL host='localhost'"
      state: present

  # installing WordPress via wp-cli

  - name: Download WordPress to domain directory via wp-cli
    command: wp core download
    args:
      chdir: '/home/{{ remote_web_user }}/www/{{ domain }}'

  - name: Setup WordPress Config using wp-cli
    command: wp config create --dbname={{ wpdbname|quote }} --dbuser={{ wpdbname|quote }} --dbpass={{db_pass.stdout|quote}}
    args:
      chdir: '/home/{{ remote_web_user }}/www/{{ domain }}'

  - name: Install WordPress using wp-cli
    command: wp core install --url={{ domain|quote }} --title={{ wpsitetitle|quote }} --admin_user={{ wpuser|quote }} --admin_password={{ wppass|quote }} --admin_email={{ wpemail|quote }}
    args:
      chdir: '/home/{{ remote_web_user }}/www/{{ domain }}'

  become: yes
  become_user: "{{ remote_web_user }}"