---
# sets up all nginx sites configurations

- name: debugging domains var.
  debug:
    var: domains

- name: Copy configurations to new domain based configuration.
  copy:
    remote_src: yes
    src: "{{ item.1.src }}"
    dest: "{{ nginx_defaults.file_path }}/{{ item.0.name }}.{{ item.1.type }}.conf"
    force: no
  with_nested:
    - "{{ domains }}"
    - "{{ nginx_defaults.single_wp_site }}"

- name: Modify root path directive configuration for configurations
  replace:
    dest: "{{ nginx_defaults.file_path }}/{{ item.0.name }}.{{ item.1.type }}.conf"
    regexp: "{{ item.1.root_path_regex }}"
    replace: '\1/home/{{ remote_web_user }}/www/{{ item.0.name }}\2'
  with_nested:
    - "{{ domains }}"
    - "{{ nginx_defaults.single_wp_site }}"

- name: Replace template domain in configurations file with the actual domain
  replace:
    path: "{{ nginx_defaults.file_path }}/{{ item.0.name }}.{{ item.1.type }}.conf"
    regexp: "{{ item.1.domain_regex }}"
    replace: '\1{{ item.0.name }}\2'
  with_nested:
    - "{{ domains }}"
    - "{{ nginx_defaults.single_wp_site }}"

## Modify lets encrypt to point to its own folder
- name: Modify lets encrypt to point to its own folder for authorization (nonssl)
  replace:
    path: "{{ nginx_defaults.file_path }}/{{ item.0.name }}.{{ item.1.type }}.conf"
    regexp: "{{ nginx_defaults.letsencrypt_regex }}"
    replace: '\1/home/{{ remote_web_user }}/www/letsencrypt\2'
  with_nested:
    - "{{ domains }}"
    - "{{ nginx_defaults.single_wp_site }}"

## Modify access_log_path directive
- name: Modify access_log path directive for configurations.
  lineinfile:
    dest: "{{ nginx_defaults.file_path}}/{{ item.0.name }}.{{ item.1.type }}.conf"
    regexp: "access_log"
    line: "access_log /home/{{ remote_web_user }}/www/{{ item.0.name }}/logs/access.log;"
    state: present
  with_nested:
    - "{{ domains }}"
    - "{{ nginx_defaults.single_wp_site }}"


## modify error_log path directives
- name: Modify error_log path directive for all domain
  lineinfile:
    dest: "{{ nginx_defaults.file_path}}/{{ item.0.name }}.{{ item.1.type }}.conf"
    regexp: "error_log"
    line: "error_log /home/{{ remote_web_user }}/www/{{ item.0.name }}/logs/error.log;"
    state: present
  with_nested:
    - "{{ domains }}"
    - "{{ nginx_defaults.single_wp_site }}"

## symlink non ssl domain for nginx (ssl domain symlink happens in letsencrypt role)
- name: Symlink non ssl domain (ssl domain symlink happens in letsencrypt role)
  file:
    src: "{{ nginx_defaults.file_path }}/{{ item.name }}.{{ nginx_defaults.non_ssl_ext }}"
    dest: "{{ nginx_defaults.file_path_enabled }}/{{ item.name }}.{{ nginx_defaults.non_ssl_ext }}"
    state: link
  notify: restart nginx
  with_items:
    - "{{ domains }}"